# ---------------------------------
# The Event Producer: PingSource
# ---------------------------------
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: cron-ping-source
spec:
  schedule: "* * * * *" # Fire an event once every minute
  contentType: "application/json"
  data: '{"message": "Hello from Knative Eventing!"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
# ---------------------------------
# The Simple Event Consumer: Go Application
# ---------------------------------
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/tomconn/event-display:latest